In [1]:
# ============================================================
# SECTION 1 : IMPORT LIBRARIES
# ============================================================

import pandas as pd
import zipfile
import os
import glob

In [2]:
# ============================================================
# SECTION 2 : DEFINE FILE PATHS
# ============================================================

zip_file = "Datasets-shoping-app-main.zip"
extract_folder = "shopping_dataset"

In [3]:
# ============================================================
# SECTION 3 : EXTRACT ZIP FILE
# ============================================================

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

print("ZIP file extracted successfully!")

ZIP file extracted successfully!

In [4]:
# ============================================================
# SECTION 4 : VIEW EXTRACTED FILES
# ============================================================

os.listdir(extract_folder)

['Datasets-shoping-app-main']

In [5]:
# ============================================================
# SECTION 5 : FIND ALL CSV FILES
# ============================================================

csv_files = glob.glob(
    extract_folder + "/**/*.csv",
    recursive=True
)

print(csv_files)

['shopping_dataset/Datasets-shoping-app-main/formal-shoes.csv', 'shopping_dataset/Datasets-shoping-app-main/runners.csv', 'shopping_dataset/Datasets-shoping-app-main/co-ords.csv', 'shopping_dataset/Datasets-shoping-app-main/lounge-shorts.csv', 'shopping_dataset/Datasets-shoping-app-main/face-wash-and-cleanser.csv', 'shopping_dataset/Datasets-shoping-app-main/hair-masks.csv', 'shopping_dataset/Datasets-shoping-app-main/sports-shoes.csv', 'shopping_dataset/Datasets-shoping-app-main/towel-set.csv', 'shopping_dataset/Datasets-shoping-app-main/gloves.csv', 'shopping_dataset/Datasets-shoping-app-main/hair-cream-and-mask.csv', 'shopping_dataset/Datasets-shoping-app-main/trunk.csv', 'shopping_dataset/Datasets-shoping-app-main/bodysuit.csv', 'shopping_dataset/Datasets-shoping-app-main/watches.csv', 'shopping_dataset/Datasets-shoping-app-main/tunics.csv', 'shopping_dataset/Datasets-shoping-app-main/kurtis.csv', 'shopping_dataset/Datasets-shoping-app-main/dinnerware.csv', 'shopping_dataset/Datasets-shoping-app-main/face-moisturisers.csv', 'shopping_dataset/Datasets-shoping-app-main/cutlery.csv', 'shopping_dataset/Datasets-shoping-app-main/showpieces.csv', 'shopping_dataset/Datasets-shoping-app-main/outdoor-masks.csv', 'shopping_dataset/Datasets-shoping-app-main/headphones.csv', 'shopping_dataset/Datasets-shoping-app-main/boots.csv', 'shopping_dataset/Datasets-shoping-app-main/dupatta.csv', 'shopping_dataset/Datasets-shoping-app-main/innerwear-vests.csv', 'shopping_dataset/Datasets-shoping-app-main/mangalsutra.csv', 'shopping_dataset/Datasets-shoping-app-main/bath-towels.csv', 'shopping_dataset/Datasets-shoping-app-main/yoga-mats.csv', 'shopping_dataset/Datasets-shoping-app-main/jackets.csv', 'shopping_dataset/Datasets-shoping-app-main/sweatshirts.csv', 'shopping_dataset/Datasets-shoping-app-main/shampoo-and-conditioner.csv', 'shopping_dataset/Datasets-shoping-app-main/briefs.csv', 'shopping_dataset/Datasets-shoping-app-main/earrings.csv', 'shopping_dataset/Datasets-shoping-app-main/lounge-pants.csv', 'shopping_dataset/Datasets-shoping-app-main/nightdress.csv', 'shopping_dataset/Datasets-shoping-app-main/thermal-bottoms.csv', 'shopping_dataset/Datasets-shoping-app-main/scarves.csv', 'shopping_dataset/Datasets-shoping-app-main/tights.csv', 'shopping_dataset/Datasets-shoping-app-main/tops.csv', 'shopping_dataset/Datasets-shoping-app-main/sarees.csv', 'shopping_dataset/Datasets-shoping-app-main/tshirts.csv', 'shopping_dataset/Datasets-shoping-app-main/hair-brush-and-comb.csv', 'shopping_dataset/Datasets-shoping-app-main/shorts.csv', 'shopping_dataset/Datasets-shoping-app-main/table-covers.csv', 'shopping_dataset/Datasets-shoping-app-main/kurtas.csv', 'shopping_dataset/Datasets-shoping-app-main/sherwani.csv', 'shopping_dataset/Datasets-shoping-app-main/caps.csv', 'shopping_dataset/Datasets-shoping-app-main/swim-tops.csv', 'shopping_dataset/Datasets-shoping-app-main/dungarees.csv', 'shopping_dataset/Datasets-shoping-app-main/foundation.csv', 'shopping_dataset/Datasets-shoping-app-main/trolley-bag.csv', 'shopping_dataset/Datasets-shoping-app-main/floor-mats--dhurries.csv', 'shopping_dataset/Datasets-shoping-app-main/handbags.csv', 'shopping_dataset/Datasets-shoping-app-main/track-pants.csv', 'shopping_dataset/Datasets-shoping-app-main/sandals.csv', 'shopping_dataset/Datasets-shoping-app-main/jeans.csv', 'shopping_dataset/Datasets-shoping-app-main/bath-robe.csv', 'shopping_dataset/Datasets-shoping-app-main/palazzos.csv', 'shopping_dataset/Datasets-shoping-app-main/bracelet.csv', 'shopping_dataset/Datasets-shoping-app-main/duffel-bag.csv', 'shopping_dataset/Datasets-shoping-app-main/lounge-tshirts.csv', 'shopping_dataset/Datasets-shoping-app-main/pillow-covers.csv', 'shopping_dataset/Datasets-shoping-app-main/shaving-essentials.csv', 'shopping_dataset/Datasets-shoping-app-main/backpacks.csv', 'shopping_dataset/Datasets-shoping-app-main/curtains-and-sheers.csv', 'shopping_dataset/Datasets-shoping-app-main/casual-shoes.csv', 'shopping_dataset/Datasets-shoping-app-main/shirts.csv', 'shopping_dataset/Datasets-shoping-app-main/kurta-sets.csv', 'shopping_dataset/Datasets-shoping-app-main/skirts.csv', 'shopping_dataset/Datasets-shoping-app-main/sweaters.csv', 'shopping_dataset/Datasets-shoping-app-main/candle-holders.csv', 'shopping_dataset/Datasets-shoping-app-main/flip-flops.csv', 'shopping_dataset/Datasets-shoping-app-main/home-fragrance-set.csv', 'shopping_dataset/Datasets-shoping-app-main/mobile-accessories.csv', 'shopping_dataset/Datasets-shoping-app-main/belts.csv', 'shopping_dataset/Datasets-shoping-app-main/saree-blouse.csv', 'shopping_dataset/Datasets-shoping-app-main/sunglasses.csv', 'shopping_dataset/Datasets-shoping-app-main/clothing-set.csv', 'shopping_dataset/Datasets-shoping-app-main/bedsheets.csv', 'shopping_dataset/Datasets-shoping-app-main/ethnic-dresses.csv', 'shopping_dataset/Datasets-shoping-app-main/bra.csv', 'shopping_dataset/Datasets-shoping-app-main/ring.csv', 'shopping_dataset/Datasets-shoping-app-main/dresses.csv', 'shopping_dataset/Datasets-shoping-app-main/wall-art.csv', 'shopping_dataset/Datasets-shoping-app-main/jumpsuit.csv', 'shopping_dataset/Datasets-shoping-app-main/flats.csv', 'shopping_dataset/Datasets-shoping-app-main/hair-accessory.csv', 'shopping_dataset/Datasets-shoping-app-main/bathroom-accessories.csv', 'shopping_dataset/Datasets-shoping-app-main/heels.csv', 'shopping_dataset/Datasets-shoping-app-main/trousers.csv', 'shopping_dataset/Datasets-shoping-app-main/wallets.csv', 'shopping_dataset/Datasets-shoping-app-main/clutches.csv', 'shopping_dataset/Datasets-shoping-app-main/perfume-and-body-mist.csv', 'shopping_dataset/Datasets-shoping-app-main/lipstick.csv', 'shopping_dataset/Datasets-shoping-app-main/boxers.csv', 'shopping_dataset/Datasets-shoping-app-main/night-suits.csv', 'shopping_dataset/Datasets-shoping-app-main/camisoles.csv', 'shopping_dataset/Datasets-shoping-app-main/chair-cover.csv']

In [6]:
# ============================================================
# SECTION 6 : LOAD ALL CSV FILES
# ============================================================

dataframes = []

for file in csv_files:
    df = pd.read_csv(file)
    dataframes.append(df)

print("All CSV files loaded successfully!")

All CSV files loaded successfully!

In [7]:
# ============================================================
# SECTION 7 : COMBINE ALL DATAFRAMES
# ============================================================

combined_df = pd.concat(
    dataframes,
    ignore_index=True
)

print("All CSV files combined successfully!")

All CSV files combined successfully!

In [8]:
# ============================================================
# SECTION 8 : SAVE COMBINED DATASET
# ============================================================

combined_df.to_csv(
    "combine_shopping_dataset.csv",
    index=False
)

print("Combined dataset saved!")

Combined dataset saved!

In [9]:
# ============================================================
# SECTION 9 : DISPLAY FIRST 5 ROWS
# ============================================================

combined_df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,1848495,Teakwood Leathers,Men Brown Leather Formal Shoes,3.5,25,10199.0,60.0,"""₹4,079.00""",INR,http://assets.myntassets.com/assets/images/184...,...,"{""1_star"":5,""2_stars"":3,""3_stars"":3,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",TEA███OD,"[{""size"":""6"",""value"":""25.0cm"",""value_name"":""To...",NaN,"SF-███ MG███AD,█████████R, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
1,21850100,FAUSTO,Men Formal Lace-Up Oxfords Shoes,0.0,0,999.0,1.0,"""₹989.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,STY███HOR███MAR█████████IVA████████████,"[{""size"":""6"",""value"":""25.5cm"",""value_name"":""To...",NaN,40A███ Ma███ Mo█████████ya ███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
2,19778366,EZOK,Men Brown Leather Textured Formal Derbys,0.0,0,4299.0,34.0,"""₹2,837.00""",INR,http://assets.myntassets.com/assets/images/197...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Ama███hoe███nd █████████are███,"[{""size"":""6"",""value"":""26.0cm"",""value_name"":""To...",NaN,"C-7███cto███80,█████████r P███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
3,21869550,San Frissco,Men Genuine Leather Formal Loafers,0.0,0,7995.0,63.0,"""₹2,958.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,ARY███ FO███EAR█████████PVT██████,"[{""size"":""6"",""value"":""24.9cm"",""value_name"":""To...",NaN,Ary███ fo███ear█████████vt ███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
4,21931392,Clarks,Men Leather Round Toe Formal Derbys,4.4,7,9999.0,40.0,"""₹5,999.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",CLA███ RE███NCE█████████ PV██████,"[{""size"":""6"",""value"":""24.6cm"",""value_name"":""To...",NaN,"Kil███o. ███/ 1█████████, 1███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes

In [10]:
# ============================================================
# SECTION 10 : DISPLAY LAST 5 ROWS
# ============================================================

combined_df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,18209958,Sweet Dreams,Men Black Solid Casual Night suit,4.1,13,2099.0,44.0,"""₹2,099.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",night-suits
996,15973760,Zoom Minimondo,Unisex Kids Magenta & Blue Pure Cotton Night suit,4.8,10,1299.0,69.0,"""₹402.00""",INR,http://assets.myntassets.com/assets/images/159...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,KCJ███RKE███G P█████████MIT███,"[{""size"":""7-8Y"",""value"":""34.0in"",""value_name"":...",NaN,SAD███D D███AVA█████████OP ███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 599 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",night-suits
997,21877640,DressBerry,Shoulder Straps Pure Cotton Camisole,3.7,14,299.0,23.0,"""₹230.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,VAC███CRE███ONS███,"[{""size"":""S"",""value"":""30.0in"",""value_name"":""To...",NaN,"870███TRE███SHE█████████, B███████████████████...","[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",camisoles
998,18882294,VStar,Women White Solid Modern Fit Deep Neckline Ca...,4.8,10,265.0,NaN,"""₹265.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,V S███ CR███ION█████████,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""T...",NaN,VI/███ AB███ ST█████████ODE███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",camisoles
999,21937664,Cortina,Black & Beige 4 Pcs Ethnic Motif Printed Super...,4.7,15,2598.0,64.0,"""₹935.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bha███vna███Imp█████████ect███,"[{""size"":""Onesize""}]",NaN,Plo███o.2███1 A█████████ust███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",chair-cover

In [11]:
# ============================================================
# SECTION 11 : CHECK DATASET SHAPE
# ============================================================

combined_df.shape

(1000, 24)

In [12]:
# ============================================================
# SECTION 12 : DISPLAY COLUMN NAMES
# ============================================================

combined_df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [13]:
# ============================================================
# SECTION 13 : CHECK DATA TYPES
# ============================================================

combined_df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [14]:
# ============================================================
# SECTION 14 : DISPLAY DATASET INFO
# ============================================================

combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   float64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(3), int64(2), object(19)
memory usage: 187.6+ KB

In [15]:
# ============================================================
# SECTION 15 : CHECK MISSING VALUES
# ============================================================

combined_df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [16]:
# ============================================================
# SECTION 16 : FILL MISSING VALUES
# ============================================================

combined_df.fillna(
    "Unknown",
    inplace=True
)

combined_df.isnull().sum()

/tmp/ipykernel_4642/3627134692.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  combined_df.fillna(

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [17]:
# ============================================================
# SECTION 17 : DROP NULL VALUES
# ============================================================

combined_df.dropna(inplace=True)

combined_df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [18]:
# ============================================================
# SECTION 18 : SELECT IMPORTANT COLUMNS
# ============================================================

combined_df[
    ["title", "rating", "final_price"]
]

                 title  rating  final_price
0    Teakwood Leathers     3.5  "₹4,079.00"
1               FAUSTO     0.0    "₹989.00"
2                 EZOK     0.0  "₹2,837.00"
3          San Frissco     0.0  "₹2,958.00"
4               Clarks     4.4  "₹5,999.00"
..                 ...     ...          ...
995       Sweet Dreams     4.1  "₹2,099.00"
996     Zoom Minimondo     4.8    "₹402.00"
997         DressBerry     3.7    "₹230.00"
998              VStar     4.8    "₹265.00"
999            Cortina     4.7    "₹935.00"

[1000 rows x 3 columns]

In [19]:
# ============================================================
# SECTION 19 : FILTER HIGH RATED PRODUCTS
# ============================================================

high_rating = combined_df[
    combined_df["rating"] > 4
]

high_rating.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
4,21931392,Clarks,Men Leather Round Toe Formal Derbys,4.4,7,9999.0,40.0,"""₹5,999.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",CLA███ RE███NCE█████████ PV██████,"[{""size"":""6"",""value"":""24.6cm"",""value_name"":""To...",Unknown,"Kil███o. ███/ 1█████████, 1███████████████████...",Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes
13,10018911,SEJ by Nisha Gupta,Multicoloured Printed Table Runner,4.5,13,1849.0,70.0,"""₹554.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,SEJ███RNI███NGS█████████LIM██████,"[{""size"":""Onesize""}]",Unknown,K-1███ST ███OR █████████AGA███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",runners
15,16694464,Ahalyaa,Women Stunning Blue Printed Top with Solid Skirt,4.1,195,5000.0,66.0,"""₹1,700.00""",INR,http://assets.myntassets.com/assets/images/166...,...,"{""1_star"":17,""2_stars"":8,""3_stars"":18,""4_stars...",Unknown,UDA███ASH███,"[{""size"":""S"",""value"":""15.0in"",""value_name"":""Fr...",Unknown,1ST███OOR███D 2█████████ PL███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",co-ords
16,18273822,Dreamz by Pantaloons,Women Grey & White Striped Cotton Lounge Shorts,4.5,15,499.0,2.0,"""₹489.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",Unknown,Wes███ry ███din█████████d_P████████████,"[{""size"":""M"",""value"":""26.0in"",""value_name"":""Ga...",Unknown,Wes███ry ███din█████████e L███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",lounge-shorts
17,12926546,natural vibes,Unisex Ayurvedic Teatree Facewash 150ml,4.8,9,449.0,5.0,"""₹426.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",Unknown,TRA███LA ███OM █████████,"[{""size"":""125-150 ML""}]",Unknown,"C7 ███T N███29,█████████RLD███████████████████...",Unknown,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",face-wash-and-cleanser

In [20]:
# ============================================================
# SECTION 20 : REMOVE DUPLICATES
# ============================================================

combined_df.drop_duplicates(
    inplace=True
)

print("Duplicate rows removed!")

Duplicate rows removed!

In [21]:
# ============================================================
# SECTION 21 : CREATE QUANTITY COLUMN
# ============================================================

combined_df["quantity"] = 2

In [22]:
# ============================================================
# SECTION 22 : CREATE TOTAL_AMOUNT COLUMN
# ============================================================

combined_df["total_amount"] = (
    combined_df["final_price"] *
    combined_df["quantity"]
)

In [23]:
# ============================================================
# SECTION 23 : SAVE CLEANED DATASET
# ============================================================

combined_df.to_csv(
    "cleaned_shopping_dataset.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [24]:
# ============================================================
# SECTION 24 : FINAL DATASET PREVIEW
# ============================================================

combined_df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,1848495,Teakwood Leathers,Men Brown Leather Formal Shoes,3.5,25,10199.0,60.0,"""₹4,079.00""",INR,http://assets.myntassets.com/assets/images/184...,...,TEA███OD,"[{""size"":""6"",""value"":""25.0cm"",""value_name"":""To...",Unknown,"SF-███ MG███AD,█████████R, ███████████████████...",Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes,2,"""₹4,079.00""""₹4,079.00"""
1,21850100,FAUSTO,Men Formal Lace-Up Oxfords Shoes,0.0,0,999.0,1.0,"""₹989.00""",INR,http://assets.myntassets.com/assets/images/218...,...,STY███HOR███MAR█████████IVA████████████,"[{""size"":""6"",""value"":""25.5cm"",""value_name"":""To...",Unknown,40A███ Ma███ Mo█████████ya ███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes,2,"""₹989.00""""₹989.00"""
2,19778366,EZOK,Men Brown Leather Textured Formal Derbys,0.0,0,4299.0,34.0,"""₹2,837.00""",INR,http://assets.myntassets.com/assets/images/197...,...,Ama███hoe███nd █████████are███,"[{""size"":""6"",""value"":""26.0cm"",""value_name"":""To...",Unknown,"C-7███cto███80,█████████r P███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes,2,"""₹2,837.00""""₹2,837.00"""
3,21869550,San Frissco,Men Genuine Leather Formal Loafers,0.0,0,7995.0,63.0,"""₹2,958.00""",INR,http://assets.myntassets.com/assets/images/218...,...,ARY███ FO███EAR█████████PVT██████,"[{""size"":""6"",""value"":""24.9cm"",""value_name"":""To...",Unknown,Ary███ fo███ear█████████vt ███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes,2,"""₹2,958.00""""₹2,958.00"""
4,21931392,Clarks,Men Leather Round Toe Formal Derbys,4.4,7,9999.0,40.0,"""₹5,999.00""",INR,http://assets.myntassets.com/assets/images/219...,...,CLA███ RE███NCE█████████ PV██████,"[{""size"":""6"",""value"":""24.6cm"",""value_name"":""To...",Unknown,"Kil███o. ███/ 1█████████, 1███████████████████...",Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",formal-shoes,2,"""₹5,999.00""""₹5,999.00"""